plugins:
  - jekyll-remote-theme

title: WX's homepage

skin: daylight

email: 452447241@qq.com

avatar: /logo.png

location: Nanjing University

subscribe: true

remote_theme: ngzhio/jekyll-theme-hamilton